# Generated by Django 6.0.4 on 2026-04-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="Дата и время начала рассылки", verbose_name="Дата и время начала рассылки"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="Дата и время окончания рассылки", verbose_name="Дата и время окончания рассылки"
                    ),
                ),
                (
                    "status",
                    models.CharField(help_text="Статус рассылки", max_length=9, verbose_name="Статус рассылки"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Messages",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(help_text="Тема рассылки", max_length=200, verbose_name="Тема рассылки")),
                ("mail_body", models.TextField(help_text="Комментарий", verbose_name="Комментарий")),
            ],
        ),
        migrations.CreateModel(
            name="Recipients",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="ФИО получателя рассылки", max_length=200, verbose_name="ФИО получателя"
                    ),
                ),
                (
                    "email",
                    models.EmailField(help_text="Email получателя рассылки", max_length=254, verbose_name="email"),
                ),
                ("comment", models.TextField(blank=True, help_text="Комментарий", verbose_name="Комментарий")),
            ],
        ),
        migrations.CreateModel(
            name="work_mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attempt_time",
                    models.DateTimeField(help_text="Дата и время рассылки", verbose_name="Дата и время рассылки"),
                ),
                ("status", models.BooleanField(default=False)),
                ("server_response", models.TextField(help_text="Ответ сервера", verbose_name="Ответ сервера")),
            ],
        ),
    ]
