# Generated by Django 6.0.4 on 2026-04-16 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sending_mail", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Владелец рассылки",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailing",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец рассылки",
            ),
        ),
        migrations.AddField(
            model_name="messages",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Владелец сообщения",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец сообщения",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                help_text="Рассылка",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message",
                to="sending_mail.messages",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AddField(
            model_name="recipients",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Владелец получателя",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец получателя",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(to="sending_mail.recipients"),
        ),
        migrations.AddField(
            model_name="work_mailing",
            name="mailing",
            field=models.ForeignKey(
                help_text="Рассылка",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_mailing",
                to="sending_mail.mailing",
                verbose_name="Рассылка",
            ),
        ),
    ]
