# Generated by Django 6.0.4 on 2026-04-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sending_mail", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"ordering": ["message"], "verbose_name": "Рассылка", "verbose_name_plural": "Рассылки"},
        ),
        migrations.AlterModelOptions(
            name="messages",
            options={"ordering": ["subject"], "verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
        migrations.AlterModelOptions(
            name="recipients",
            options={"ordering": ["name"], "verbose_name": "Получатель", "verbose_name_plural": "Получатели"},
        ),
        migrations.AlterModelOptions(
            name="work_mailing",
            options={
                "ordering": ["mailing"],
                "verbose_name": "Состояние рассылки",
                "verbose_name_plural": "Состояние рассылок",
            },
        ),
    ]
