# Generated by Django 6.0.4 on 2026-04-16 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sending_mail", "0003_alter_mailing_options_alter_messages_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="work_mailing",
            new_name="WorkMailing",
        ),
    ]
