# Generated by Django 6.0.4 on 2026-04-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_mail", "0004_rename_work_mailing_workmailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipients",
            name="email",
            field=models.EmailField(
                help_text="Email получателя рассылки", max_length=254, unique=True, verbose_name="email"
            ),
        ),
    ]
