# Generated by Django 6.0.4 on 2026-04-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_mail", "0005_alter_recipients_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[("created", "Создана"), ("started", "Запущена"), ("completed", "Завершена")],
                default="created",
                help_text="Статус рассылки",
                max_length=9,
                verbose_name="Статус рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="mail_body",
            field=models.TextField(help_text="Текст рассылки", verbose_name="Текст рассылки"),
        ),
        migrations.AlterField(
            model_name="workmailing",
            name="status",
            field=models.CharField(
                choices=[("success", "Успешно"), ("failed", "Не успешно")],
                help_text="Статус выполения рассылки",
                max_length=10,
                verbose_name="Статус выполнения рассылки",
            ),
        ),
    ]
