# Generated by Django 6.0.4 on 2026-04-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_mail", "0006_alter_mailing_status_alter_messages_mail_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Получатели рассылки", to="sending_mail.recipients", verbose_name="Получатели рассылки"
            ),
        ),
    ]
