# Generated by Django 6.0.4 on 2026-04-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_mail", "0007_alter_mailing_recipients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(help_text="ДД.ММ.ГГГГ ЧЧ:ММ", verbose_name="Дата и время окончания рассылки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Множественный выбор через CTRL",
                to="sending_mail.recipients",
                verbose_name="Получатели рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(help_text="ДД.ММ.ГГГГ ЧЧ:ММ", verbose_name="Дата и время начала рассылки"),
        ),
    ]
