# Generated by Django 6.0.4 on 2026-04-22 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_mail", "0008_alter_mailing_end_time_alter_mailing_recipients_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workmailing",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Владелец рассылки",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_mailing_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец рассылки",
            ),
        ),
        migrations.AddField(
            model_name="workmailing",
            name="recipient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_mailing_recipient",
                to="sending_mail.recipients",
                verbose_name="Получатель рассылки",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активность рассылки"),
        ),
    ]
