# Generated by Django 6.0.4 on 2026-04-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_mail", "0009_workmailing_owner_workmailing_recipient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workmailing",
            name="server_response",
            field=models.TextField(blank=True, help_text="Ответ сервера", verbose_name="Ответ сервера"),
        ),
    ]
