# Generated by Django 6.0.4 on 2026-04-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sending_mail", "0010_alter_workmailing_server_response"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["message"],
                "permissions": [
                    ("can_view_mailing", "Может просматривать рассылки"),
                    ("can_moderated_mailing", "Может модерировать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="messages",
            options={
                "ordering": ["subject"],
                "permissions": [("can_view_message", "Может просматривать сообщения")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipients",
            options={
                "ordering": ["name"],
                "permissions": [("can_view_recipient", "Может просматривать получателей")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
